//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilboard.Api.Resources.BilboardItem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bilboard.Api.Resources.BilboardItem.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [bilboard].[BilboardItem] 
        ///(
        ///    [CreateUser_Id], 
        ///    [CreateDate], 
        ///    [IsActive], 
        ///    [Bilboard_Id], 
        ///    [Hours], 
        ///    [Task_Id]
        ///)
        ///VALUES
        ///(
        ///    @CreateUserId,               -- Użytkownik tworzący
        ///    GETDATE(),                   -- Data utworzenia (aktualna data i godzina)
        ///    1,                           -- Aktywność (1 = aktywna, 0 = nieaktywna)
        ///    @BilboardId,                 -- ID billboardu
        ///    @Hours,                      -- Liczba godzin (może być NULL, jeśli nie dotyczy)
        ///    @Task [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bilboard_BilboardItem_Create {
            get {
                return ResourceManager.GetString("Bilboard_BilboardItem_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [bilboard].[BilboardItem]
        ///SET
        ///    [ModifyUser_Id] = @UserId,       -- Ustaw użytkownika modyfikującego rekord
        ///    [ModifyDate] = GETDATE(),             -- Zaktualizuj datę modyfikacji
        ///    [IsActive] = 0                    -- Zaktualizuj identyfikator zadania
        ///WHERE 
        ///    [Id] = @BilboardItemId; .
        /// </summary>
        internal static string Bilboard_BilboardItem_Delete {
            get {
                return ResourceManager.GetString("Bilboard_BilboardItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	   [BI].[Id]
        ///	  ,[T].[Id] AS TaskId
        ///      ,[T].[External_Id] AS TaskExternalId
        ///  FROM 
        ///  [bilboard].[BilboardItem] AS [BI] (NOLOCK)
        ///  INNER JOIN [bilboard].[Task] AS [T] (NOLOCK) ON [BI].[Task_Id] = [T].[Id]
        ///  WHERE
        ///  [BI].[IsActive] = 1
        ///  AND [T].[IsActive] = 1
        ///  AND [BI].[Id] = @BilboardItemId.
        /// </summary>
        internal static string Bilboard_BilboardItem_Get {
            get {
                return ResourceManager.GetString("Bilboard_BilboardItem_Get", resourceCulture);
            }
        }
    }
}
