version: '3.4'

services:
  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: User.Api/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8000:80"
      - "8010:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - E:\\UserApp\\Files:/var/files
      - C:\\certs:/app/clientcertificate/  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${USER_DB_CONNECTION}
      - JWT__JWTPrivateKey=${JWT_PRIVATE_KEY}
      - Email__User=${EMAIL_USER}
      - Email__Password=${EMAIL_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/clientcertificate/appcert.pfx
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_HTTPS_PORTS=8010

  task.api:
    image: ${DOCKER_REGISTRY-}taskapi
    build:
      context: .
      dockerfile: Task.Api/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8001:80"
      - "8011:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - E:\\UserApp\\Files:/var/files
      - C:\\certs:/app/clientcertificate/  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${TASK_DB_CONNECTION}
      - Email__User=${EMAIL_USER}
      - Email__Password=${EMAIL_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/clientcertificate/appcert.pfx
      - ASPNETCORE_HTTP_PORTS=8001
      - ASPNETCORE_HTTPS_PORTS=8011


  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8002:80"
      - "8012:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - E:\\UserApp\\Files:/var/files
      - C:\\certs:/app/clientcertificate/  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/clientcertificate/appcert.pfx
      - ASPNETCORE_HTTP_PORTS=8002
      - ASPNETCORE_HTTPS_PORTS=8012


  bilboard.api:
    image: ${DOCKER_REGISTRY-}bilboardapi
    build:
      context: .
      dockerfile: Bilboard.Api/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8003:80"
      - "8013:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - E:\\UserApp\\Files:/var/files
      - C:\\certs:/app/clientcertificate/  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${BILBOARD_DB_CONNECTION}
      - Email__User=${EMAIL_USER}
      - Email__Password=${EMAIL_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/clientcertificate/appcert.pfx
      - ASPNETCORE_HTTP_PORTS=8003
      - ASPNETCORE_HTTPS_PORTS=8013

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmqdata:/var/log/rabbitmq
    hostname: "rabbitmq"

volumes:
  rabbitmqdata:

