//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Api.Resources.Tasks.TaskFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task.Api.Resources.Tasks.TaskFile.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [task].[TaskFile] 
        ///(
        ///    [CreateUser_Id], 
        ///    [CreateUserDate], 
        ///    [Task_Id], 
        ///    [Guid], 
        ///    [FileName],
        ///    [User_Id],
        ///    [RoleStrongName]
        ///)
        ///VALUES
        ///(
        ///    @UserId,
        ///    GETDATE(),
        ///    @TaskId,
        ///    @Guid,
        ///    @FileName,
        ///    @UserId,
        ///    @RoleStrongName
        ///);
        ///
        ///SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string Task_TaskFile_Create {
            get {
                return ResourceManager.GetString("Task_TaskFile_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [task].[TaskFile]
        ///SET 
        ///    [IsActive] = 0, 
        ///    [ModifyUser_Id] = @UserId,
        ///    [ModifyDate] = GETDATE() 
        ///WHERE 
        ///    [Id] = @FileId;  .
        /// </summary>
        internal static string Task_TaskFile_Delete {
            get {
                return ResourceManager.GetString("Task_TaskFile_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [Id],
        ///    [Task_Id] AS TaskId, 
        ///    [Guid], 
        ///    [FileName],
        ///    [User_Id] AS UserId,
        ///    [RoleStrongName]
        ///FROM 
        ///    [task].[TaskFile]
        ///WHERE 
        ///    [IsActive] = 1 
        ///    AND [Id] = @Id;.
        /// </summary>
        internal static string Task_TaskFile_Get {
            get {
                return ResourceManager.GetString("Task_TaskFile_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    [Id],
        ///    [Task_Id] AS TaskId, 
        ///    [Guid], 
        ///    [FileName],
        ///    [User_Id] AS UserId,
        ///    [RoleStrongName]
        ///FROM 
        ///    [task].[TaskFile]
        ///WHERE 
        ///    [IsActive] = 1 
        ///    AND [Task_Id] = @TaskId;.
        /// </summary>
        internal static string Task_TaskFile_GetList {
            get {
                return ResourceManager.GetString("Task_TaskFile_GetList", resourceCulture);
            }
        }
    }
}
