//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User.Api.Resources.RefreshToken {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("User.Api.Resources.RefreshToken.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [user].[Token] 
        ///(
        ///	[CreateUser_Id], 
        ///	[CreateDate],
        ///	[ModifyUser_Id],
        ///	[ModifyDate],
        ///	[IsActive], 
        ///	[Value], 
        ///	[ExpireDate],
        ///	[User_Id]
        ///)
        ///VALUES 
        ///(
        ///	@UserId, 
        ///	GETDATE(), 
        ///	@UserId, 
        ///	GETDATE(), 
        ///	1, 
        ///	@Value, 
        ///	@ExpireDate, 
        ///	@UserId
        ///);
        ///
        ///SELECT SCOPE_IDENTITY().
        /// </summary>
        internal static string User_RefreshToken_Create {
            get {
                return ResourceManager.GetString("User_RefreshToken_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[Token]
        ///SET 
        ///[IsActive] = 0
        ///WHERE [Id] = @TokenId; -- Zamień @Id na odpowiednie Id.
        /// </summary>
        internal static string User_RefreshToken_Delete {
            get {
                return ResourceManager.GetString("User_RefreshToken_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (1) 
        ///	Id
        ///	,Value
        ///	,ExpierDate
        ///	,User_Id AS UserId
        ///FROM 
        ///	[user].[Token]
        ///WHERE 
        ///	[Value] = @Value
        ///	AND [IsActive] = 1
        ///ORDER BY [ExpireDate] DESC.
        /// </summary>
        internal static string User_RefreshToken_GetRefreshTokenByJwtToken {
            get {
                return ResourceManager.GetString("User_RefreshToken_GetRefreshTokenByJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP (1) 
        ///	Id
        ///	,Value
        ///	,ExpierDate
        ///	,User_Id AS UserId
        ///FROM 
        ///	[user].[Token]
        ///WHERE 
        ///	[Value] = @Value
        ///	AND [IsActive] = 1
        ///ORDER BY [ExpireDate] DESC.
        /// </summary>
        internal static string User_RefreshToken_GetRefreshTokenByValue {
            get {
                return ResourceManager.GetString("User_RefreshToken_GetRefreshTokenByValue", resourceCulture);
            }
        }
    }
}
