//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilboard.Api.Resources.Task {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bilboard.Api.Resources.Task.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [bilboard].[Task]
        ///SET 
        ///	[ModifyUser_Id] = @UserId,
        ///	[ModifyDate] = GETDATE(),
        ///    [Status_Id] = (SELECT [Id] FROM [bilboard].[TaskStatus] WHERE [IsActive] = 1 AND [StrongName] = @StatusStrongName)                
        ///WHERE 
        ///    [Id] = @TaskId; .
        /// </summary>
        internal static string Tasks_Task_ChangeStatus {
            get {
                return ResourceManager.GetString("Tasks_Task_ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [bilboard].[Task] (
        ///    [CreateUser_Id],
        ///    [CreateDate].
        ///    [Title],
        ///    [Deadline],
        ///    [Status_Id],
        ///    [IsImportant],
        ///	[EstimatedHours],
        ///    [External_Id]
        ///)
        ///VALUES ( 
        ///@UserId,
        ///GETDATE(),
        ///    @Title,  
        ///    @Deadline,  
        ///    1,                                                      
        ///    @IsImportant,                       
        ///	@EstimatedHours,
        ///    @ExternalId
        ///);
        ///
        ///SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string Tasks_Task_Create {
            get {
                return ResourceManager.GetString("Tasks_Task_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [bilboard].[Task]
        ///SET 
        ///	[ModifyUser_Id] = @UserId,
        ///	[ModifyDate] = GETDATE(),
        ///    [IsActive] = 0  
        ///WHERE 
        ///    [External_Id] = @ExternalId;    .
        /// </summary>
        internal static string Tasks_Task_Delete {
            get {
                return ResourceManager.GetString("Tasks_Task_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///       [T].[Id]
        ///      ,[T].[CreateUser_Id] AS CreateUserId
        ///      ,[T].[CreateDate]
        ///      ,[T].[ModifyUser_Id] AS ModifyUserId
        ///      ,[T].[ModifyDate]
        ///      ,[T].[Title]
        ///      ,[T].[Deadline]
        ///      ,[T].[IsImportant]
        ///      ,[T].[EstimatedHours]
        ///	  ,[S].[Id] AS StatusId
        ///  FROM 
        ///	 [bilboard].[Task] AS [T] (NOLOCK)
        ///	 INNER JOIN [bilboard].[TaskStatus] AS [S] (NOLOCK) ON [T].[Status_Id] = [S].[Id]
        ///  WHERE
        ///	[T].[IsActive] = 1
        ///	AND [S].[IsActive] = 1
        ///	AND [T].[Id] = @TaskId.
        /// </summary>
        internal static string Tasks_Task_Get {
            get {
                return ResourceManager.GetString("Tasks_Task_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [bilboard].[Task]
        ///SET 
        ///	[ModifyUser_Id] = @UserId,
        ///	[ModifyDate] = GETDATE(),
        ///    [Title] = @Title,
        ///    [Deadline] = @Deadline,
        ///    [Status_Id] = 1,                     
        ///    [IsImportant] = @IsImportant,
        ///    [EstimatedHours] = @EstimatedHours   
        ///WHERE 
        ///    [External_Id] = @ExternalId; .
        /// </summary>
        internal static string Tasks_Task_Update {
            get {
                return ResourceManager.GetString("Tasks_Task_Update", resourceCulture);
            }
        }
    }
}
