<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2502764a-2f29-404c-b52f-93f1a19f631b</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <DocumentationFile>Doc\$(AssemblyName).xml</DocumentationFile>
	<WarningsAsErrors>nullable</WarningsAsErrors>
	<IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.4" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.4" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\BilboardItem\Sql.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Sql.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Bilboard\Sql_Bilboard.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Sql_Bilboard.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\TaskStatus\Sql.Designer.cs">
      <DependentUpon>Sql.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\Task\Sql.Designer.cs">
      <DependentUpon>Sql.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\BilboardItem\Sql.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Sql.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Bilboard\Sql_Bilboard.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Sql_Bilboard.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TaskStatus\Sql.resx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <LastGenOutput>Sql.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Task\Sql.resx">
      <LastGenOutput>Sql.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
