//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Repositories.UserXRole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Repositories.UserXRole.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [user].[UserXRole]
        ///           ([CreateDate]
        ///           ,[CreateUser_Id]
        ///           ,[ModifyDate]
        ///           ,[ModifyUser_Id]
        ///           ,[IsActive]
        ///           ,[User_Id]
        ///           ,[Role_Id])
        ///VALUES
        ///           (GETDATE(),       -- CreateDate (obecny czas)
        ///           1,               -- CreateUser_Id (przykładowy ID użytkownika tworzącego)
        ///           NULL,            -- ModifyDate (brak modyfikacji przy tworzeniu)
        ///           NULL,            -- ModifyUser_Id (brak modyfikacji przy tworzeniu)
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_UserXRole_AddRole {
            get {
                return ResourceManager.GetString("User_UserXRole_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///       [Id] AS RoleId
        ///      ,[Name]
        ///      ,[StrongName]
        ///  FROM [user].[Role]
        ///  WHERE 
        ///  [IsActive] = 1
        ///  AND [StrongName] = @StrongName.
        /// </summary>
        internal static string User_UserXRole_GetRole {
            get {
                return ResourceManager.GetString("User_UserXRole_GetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///       [R].[Id] AS RoleId
        ///      ,[R].[Name]
        ///      ,[R].[StrongName]
        ///  FROM 
        ///    [user].[UserXRole] AS [UXR] (NOLOCK)
        ///    INNER JOIN [user].[Role] AS [R] (NOLOCK) ON [UXR].[Role_Id] = [R].[Id]
        ///  WHERE 
        ///    [UXR].[IsActive] = 1
        ///    AND [R].[IsActive] = 1
        ///    AND [UXR].[User_Id] = @UserId.
        /// </summary>
        internal static string User_UserXRole_GetRolesForUser {
            get {
                return ResourceManager.GetString("User_UserXRole_GetRolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE
        ///	[user].[UserXRole]
        ///SET 
        ///	IsActive = 0
        ///WHERE
        ///	 [User_Id] = @UserId
        ///	 AND [Role_Id] = @RoleId
        ///	 AND [IsActive] = 1
        ///.
        /// </summary>
        internal static string User_UserXRole_RemoveRole {
            get {
                return ResourceManager.GetString("User_UserXRole_RemoveRole", resourceCulture);
            }
        }
    }
}
