//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Repositories.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Repositories.User.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,
        ///    [ModifyDate] = GETDATE(), 
        ///    [Activated] = 1
        ///WHERE 
        ///    [User_Id] = @UserId;  .
        /// </summary>
        internal static string User_User_Activate {
            get {
                return ResourceManager.GetString("User_User_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,
        ///    [ModifyDate] = GETDATE(), 
        ///    [Blocked] = 1,      
        ///    [UnblockTime] = @UnblockTime
        ///WHERE 
        ///    [User_Id] = @UserId;  .
        /// </summary>
        internal static string User_User_Block {
            get {
                return ResourceManager.GetString("User_User_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,
        ///    [ModifyDate] = GETDATE(),
        ///    [PasswordHash] = @PasswordHash,
        ///    [PasswordSalt] = @PasswordSalt
        ///WHERE 
        ///    [User_Id] = @UserId;  .
        /// </summary>
        internal static string User_User_ChangePassword {
            get {
                return ResourceManager.GetString("User_User_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [user].[User] (
        ///    [CreateUser_Id],
        ///    [CreateDate],
        ///    [ModifyUser_Id],
        ///    [ModifyDate],
        ///    [IsActive],
        ///    [Email],
        ///    [FirstName],
        ///    [LastName],
        ///    [PasswordHash],
        ///    [PasswordSalt],
        ///    [Blocked],
        ///    [Activated],
        ///    [UnblockTime],
        ///    [Street],
        ///    [City],
        ///    [Country_Id],
        ///    [PostalCode],
        ///    [Culture_Id]
        ///)
        ///VALUES (
        ///    1,                          -- CreateUser_Id
        ///    GETDATE(),                  -- CreateDate
        ///    NULL,                       -- ModifyUser_Id
        ///    NULL,           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_User_Create {
            get {
                return ResourceManager.GetString("User_User_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,   -- Id użytkownika, który dokonuje modyfikacji
        ///    [ModifyDate] = GETDATE(),           -- Data modyfikacji
        ///    [IsActive] = 0
        ///WHERE 
        ///    [User_Id] = @UserId;  .
        /// </summary>
        internal static string User_User_Delete {
            get {
                return ResourceManager.GetString("User_User_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///       [U].[Id]
        ///      ,[U].[Email]
        ///      ,[U].[FirstName]
        ///      ,[U].[LastName]
        ///      ,[U].[PasswordHash]
        ///      ,[U].[PasswordSalt]
        ///      ,[U].[Blocked]
        ///      ,[U].[Activated]
        ///      ,[U].[UnblockTime]
        ///      ,[U].[Photo]
        ///      ,[U].[Street]
        ///      ,[U].[City]
        ///      ,[U].[PostalCode]
        ///	  ,[CL].[Name] AS Culture
        ///      ,[CL].[Code] AS CultureCode
        ///	  ,[CT].[Name] AS Country
        ///      ,[CT].[Code] AS CountryCode
        ///      ,(
        ///		  SELECT 
        ///			   [R].[Id]
        ///			  ,[R].[Name]
        ///			  ,[R].[StrongName]
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_User_Get {
            get {
                return ResourceManager.GetString("User_User_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///       [U].[Id]
        ///      ,[U].[Email]
        ///      ,[U].[FirstName]
        ///      ,[U].[LastName]
        ///      ,[U].[PasswordHash]
        ///      ,[U].[PasswordSalt]
        ///      ,[U].[Blocked]
        ///      ,[U].[Activated]
        ///      ,[U].[UnblockTime]
        ///      ,[U].[Photo]
        ///      ,[U].[Street]
        ///      ,[U].[City]
        ///      ,[U].[PostalCode]
        ///	  ,[CL].[Name] AS Culture
        ///      ,[CL].[Code] AS CultureCode
        ///	  ,[CT].[Name] AS Country
        ///      ,[CT].[Code] AS CountryCode
        ///	  ,(
        ///		  SELECT 
        ///			   [R].[Id]
        ///			  ,[R].[Name]
        ///			  ,[R].[StrongName]
        ///		  F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_User_GetByEmail {
            get {
                return ResourceManager.GetString("User_User_GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,
        ///    [ModifyDate] = GETDATE(), 
        ///    [Blocked] = 0
        ///WHERE 
        ///    [User_Id] = @UserId;  .
        /// </summary>
        internal static string User_User_Unblock {
            get {
                return ResourceManager.GetString("User_User_Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [user].[User]
        ///SET 
        ///    [ModifyUser_Id] = @UserId,   -- Id użytkownika, który dokonuje modyfikacji
        ///    [ModifyDate] = GETDATE(),           -- Data modyfikacji
        ///    [Email] = @Email,                   -- Nowy adres e-mail
        ///    [FirstName] = @FirstName,           -- Nowe imię
        ///    [LastName] = @LastName,
        ///    [Street] = @Street,                 -- Nowa ulica
        ///    [City] = @City,                     -- Nowe miasto
        ///    [Country_Id] = @CountryId,          -- Nowy kraj
        ///    [PostalCode] = @PostalCode,         --  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User_User_Update {
            get {
                return ResourceManager.GetString("User_User_Update", resourceCulture);
            }
        }
    }
}
